SELECT FNAME, MINIT, LNAME
FROM MIPARKE2.COM_EMPLOYEE
WHERE DNO IN (SELECT DNO
                               FROM MIPARKE2.COM_EMPLOYEE
                               WHERE SALARY IN (SELECT MAX(SALARY)
			                                  FROM MIPARKE2.COM_EMPLOYEE));

SELECT FNAME, MINIT, LNAME
FROM MIPARKE2.COM_EMPLOYEE
WHERE SUPERSSN IN (SELECT SSN
                                           FROM MIPARKE2.COM_EMPLOYEE
                                           WHERE SUPERSSN = '888665555');

SELECT FNAME, MINIT, LNAME
FROM MIPARKE2.COM_EMPLOYEE
WHERE SALARY >= (SELECT MIN(SALARY)+10000
			   FROM MIPARKE2.COM_EMPLOYEE);

